### ISSUE TITLE
[HELP] RDP Sound not working on RHEL 7.6

### ISSUE THREAD

**Issue by jsisaev1** [Zer0CoolX/guacamole-install-rhel-7#131]
**Details**
OS/Version: RHEL 7.6
Guacamole Source: Git
Any other options selected from the script prompts:

**Describe the bug**
In Chrome 83 on Win10 I have no audio present

**Error Message(s) and Logs**
`Jul  7 11:48:34 localhost guacd[2719]: Loading keymap "base"
Jul  7 11:48:34 localhost guacd: guacd[2719]: INFO:#011Loading keymap "base"
Jul  7 11:48:34 localhost guacd: guacd[2719]: INFO:#011Loading keymap "en-us-qwerty"
Jul  7 11:48:34 localhost guacd[2719]: Loading keymap "en-us-qwerty"
Jul  7 11:48:35 localhost guacd[2719]: Connected to RDPDR 1.13 as client 0x0004
Jul  7 11:48:35 localhost guacd: guacd[2719]: INFO:#011Connected to RDPDR 1.13 as client 0x0004
Jul  7 11:48:37 localhost guacd[2698]: RDP server closed connection: Disconnected by other connection.
Jul  7 11:48:37 localhost guacd: guacd[2698]: INFO:#011RDP server closed connection: Disconnected by other connection.
Jul  7 11:48:37 localhost guacd[2698]: Internal RDP client disconnected
Jul  7 11:48:37 localhost guacd: guacd[2698]: INFO:#011Internal RDP client disconnected
Jul  7 11:48:37 localhost guacd[2698]: User "@70d94984-82d6-43af-9678-756ca1f2ec99" disconnected (0 users remain)
Jul  7 11:48:37 localhost server: 11:48:37.066 [http-bio-8080-exec-8] INFO  o.a.g.tunnel.TunnelRequestService - User "j" disconnected from connection "12". Duration: 105492 milliseconds
Jul  7 11:48:37 localhost server: Exception in thread "Thread-15" java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
Jul  7 11:48:37 localhost server: at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:387)
Jul  7 11:48:37 localhost server: at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessage(WsRemoteEndpointImplBase.java:344)
Jul  7 11:48:37 localhost server: at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$TextMessageSendHandler.write(WsRemoteEndpointImplBase.java:788)
Jul  7 11:48:37 localhost server: at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:252)
Jul  7 11:48:37 localhost server: at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:195)
Jul  7 11:48:37 localhost server: at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
Jul  7 11:48:37 localhost server: at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.sendInstruction(GuacamoleWebSocketTunnelEndpoint.java:152)
Jul  7 11:48:37 localhost server: at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.access$200(GuacamoleWebSocketTunnelEndpoint.java:53)
Jul  7 11:48:37 localhost server: at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint$2.run(GuacamoleWebSocketTunnelEndpoint.java:253)
Jul  7 11:48:37 localhost guacd: guacd[2698]: INFO:#011User "@70d94984-82d6-43af-9678-756ca1f2ec99" disconnected (0 users remain)
Jul  7 11:48:37 localhost guacd: guacd[2698]: INFO:#011Last user of connection "$a1c17867-9763-4e59-823f-1ea1365a18dc" disconnected
Jul  7 11:48:37 localhost guacd[2698]: Last user of connection "$a1c17867-9763-4e59-823f-1ea1365a18dc" disconnected
Jul  7 11:48:37 localhost guacd[1124]: Connection "$a1c17867-9763-4e59-823f-1ea1365a18dc" removed.
Jul  7 11:48:37 localhost guacd: guacd[1124]: INFO:#011Connection "$a1c17867-9763-4e59-823f-1ea1365a18dc" removed.`

Guacamole version is 1.2.0, fresh install.
Authentication provided by AD.

**Comment by Zer0CoolX** [comment]
I am sorry I cannot help with this. There is a pinned issue stating that this script is not compatible with RHEL/CentOS 7.6. Additionally you are using the git source not the stable source.

Read the documentation, review the issues (especially the pinned ones) and then try using the script on a fresh install of RHEL/CentOS 7.8 via the stable source. If you run into issues with it follow the guidance in the Troubleshooting part of the wiki. If you need help after that follow the directions for submitting an issue and fill it out completely.
