### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by fachex** [Zer0CoolX/guacamole-install-rhel-7#132]
The Scrip is failing when trying to install the TOTP authenticator. It calls to a repo that does not have the correct link.
Thanks

**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y/N
2. You have read the wiki and followed its guidelines including requirements, troubleshooting, etc.? Y/N

**Details**
OS/Version: RHEL 7.6
Guacamole Source: Stable/Git?
Any other options selected from the script prompts:

**Describe the bug**

**Error Message(s) and Logs (be sure not to include sensitive/personal information!)**
If an error occurred include the exact message from the display/log.

**To Reproduce**
Steps to reproduce the behavior (example):

**Have You Found a Solution to the Issue?**
Either by manually doing something before/after the script has run or by editing the script prior to running.

**Comment by Zer0CoolX** [comment]
https://github.com/Zer0CoolX/guacamole-install-rhel-7/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)
