### ISSUE TITLE
[HELP] Does the script support in-line upgrade?

### ISSUE THREAD

**Issue by toushin-taishi** [Zer0CoolX/guacamole-install-rhel-7#133]
Hi. I have installed apache guacamole 1.1.0 using this script and is working great so far. 
My question is, (pardon as I don't have a spare server to test) does this script support in-place upgrade from 1.1.0 to 1.2.0?

Thank you very much for the script and really appreciate the effort that you have put into this.

**Comment by Zer0CoolX** [comment]
Please check the Wiki and previous closed issues. This script is only meant for clean installs and cannot be used for updating previous installations.

**Comment by riahc3** [comment]
Suggestions on upgrading?
