### ISSUE TITLE
[HELP] Using my Own Certificate After Script is Run?

### ISSUE THREAD

**Issue by eatyourpeas747** [Zer0CoolX/guacamole-install-rhel-7#138]
Curious if you would know what I need to adjust in my config file to add my own certificate into Guacamole?

**Comment by Zer0CoolX** [comment]
I cannot really help with your specific/unique setup but can give you some ideas of where to look for help or details.

First, lets clarify what sort of cert you mean. I presume you mean a SSL cert for HTTPS? (alternative examples could be an LDAPS cert or the JKS cert)

If so, I recommend reading over the official Guacamole documentation, Tomcat 7.x documentation and Nginx related documentation like: http://nginx.org/en/docs/http/configuring_https_servers.html

Additionally look at the Nginx and cert related portions of the script to get an idea for how its handled when you select self-signed or Let's Encrypt cert. This can help give you a base idea of how to implement your desired cert.

For questions related to config I would recommend asking in the official Apache Guacamole forum/mailing list. If your unable to find answers there after reading up on the matter Reddit may be another good place to ask for input.

I hope the above helps, good luck.
